<?php

namespace App\Services;

use App\Models\DocumentTemplate;
use App\Models\Opportunity;
use App\Models\Sale;

class DocumentTemplateService
{
    /** Human-readable labels for each merge tag key */
    public const TAG_LABELS = [
        'customer_name'     => 'Customer Name',
        'job_name'          => 'Job Name',
        'job_no'            => 'Job #',
        'job_site_name'     => 'Job Site Name',
        'job_site_address'  => 'Job Site Address',
        'job_site_phone'    => 'Job Site Phone',
        'job_site_email'    => 'Job Site Email',
        'pm_name'           => 'Project Manager Name',
        'pm_first_name'     => 'PM First Name',
        'pm_phone'          => 'PM Phone',
        'pm_email'          => 'PM Email',
        'insurance_company' => 'Insurance Company',
        'adjuster'          => 'Adjuster',
        'policy_number'     => 'Policy Number',
        'claim_number'      => 'Claim Number',
        'dol'               => 'Date of Loss',
        'date'                  => 'Date',
        'generated_by'          => 'Generated By',
        'special_instructions'  => 'Special Instructions',
        'notes'                 => 'Notes',
        'sale_number'           => 'Sale Number',
        'opportunity_photos_qr' => 'Opportunity Photos QR Code',
        'opportunity_qr'        => 'Opportunity Mobile QR Code',
    ];

    /**
     * Resolve all merge tags and return the rendered HTML body.
     */
    public function render(DocumentTemplate $template, Opportunity $opportunity, ?Sale $sale = null): string
    {
        $fields = $this->getDefaultFields($template, $opportunity, $sale);
        return $this->renderFromFields($template, $fields, $sale, $opportunity);
    }

    /**
     * Get default field values pre-filled from opportunity/sale data.
     * Returns only fields whose tags appear in the template body.
     * QR code tags are intentionally excluded — they are always regenerated
     * at render time and should never be user-editable form fields.
     */
    public function getDefaultFields(DocumentTemplate $template, Opportunity $opportunity, ?Sale $sale = null): array
    {
        $opportunity->loadMissing(['parentCustomer', 'jobSiteCustomer', 'projectManager']);

        $customer = $opportunity->parentCustomer;
        $jobSite  = $opportunity->jobSiteCustomer;
        $pm       = $opportunity->projectManager;

        $customerName = $customer?->company_name ?: ($customer?->name ?? '');
        $jobSiteName  = $jobSite?->company_name ?: ($jobSite?->name ?? '');
        $pmName       = $pm?->name ?? '';

        $jobSiteStreet  = $jobSite?->address ?? '';
        $jobSiteCityLine = implode(', ', array_filter([
            $jobSite?->city,
            $jobSite?->province,
            $jobSite?->postal_code,
        ]));
        $jobSiteAddress = implode('<br>', array_filter([$jobSiteStreet, $jobSiteCityLine]));

        $allVars = [
            'customer_name'        => $customerName,
            'job_name'             => $opportunity->job_name ?? '',
            'job_no'               => $opportunity->job_no ?? '',
            'job_site_name'        => $jobSiteName,
            'job_site_address'     => $jobSiteAddress,
            'job_site_phone'       => $jobSite?->phone ?? '',
            'job_site_email'       => $jobSite?->email ?? '',
            'pm_name'              => $pmName,
            'pm_first_name'        => explode(' ', trim($pmName))[0] ?? '',
            'pm_phone'             => $pm?->phone ?: ($pm?->mobile ?? ''),
            'pm_email'             => $pm?->email ?? '',
            'insurance_company'    => $jobSite?->insurance_company ?? '',
            'adjuster'             => $jobSite?->adjuster ?? '',
            'policy_number'        => $jobSite?->policy_number ?? '',
            'claim_number'         => $jobSite?->claim_number ?? '',
            'dol'                  => $jobSite?->dol ? \Carbon\Carbon::parse($jobSite->dol)->format('M j, Y') : '',
            'date'                 => now()->format('F j, Y'),
            'generated_by'         => auth()->user()?->name ?? '',
            'special_instructions' => '',
            'notes'                => '',
        ];

        if ($template->needs_sale && $sale) {
            $allVars['sale_number'] = $sale->sale_number;
            // flooring_items_table is always re-built from sale; not editable
        }

        // QR codes (opportunity_photos_qr, opportunity_qr) are intentionally
        // excluded here — they are regenerated fresh in renderFromFields.

        // Only return fields whose tags are actually used in the template body
        $body = $template->body;

        return array_filter($allVars, fn($value, $key) => str_contains($body, '{{' . $key . '}}'), ARRAY_FILTER_USE_BOTH);
    }

    /**
     * Render the template body using caller-supplied field values.
     * flooring_items_table and QR codes are always rebuilt fresh from live data.
     */
    public function renderFromFields(DocumentTemplate $template, array $fields, ?Sale $sale = null, ?Opportunity $opportunity = null): string
    {
        $body = $template->body;

        foreach ($fields as $key => $value) {
            $body = str_replace('{{' . $key . '}}', $value ?? '', $body);
        }

        // flooring_items_table is always re-rendered from live sale data
        if ($template->needs_sale && $sale && str_contains($body, '{{flooring_items_table}}')) {
            $body = str_replace('{{flooring_items_table}}', $this->buildFlooringTable($sale), $body);
        }

        // QR codes are always regenerated fresh — never stored as editable fields
        if ($opportunity) {
            if (str_contains($body, '{{opportunity_photos_qr}}')) {
                $photosUrl = route('mobile.opportunity.photos', $opportunity->id);
                $qrSvg     = (string) \SimpleSoftwareIO\QrCode\Facades\QrCode::size(100)->margin(1)->generate($photosUrl);
                $body = str_replace('{{opportunity_photos_qr}}',
                    '<img src="data:image/svg+xml;base64,' . base64_encode($qrSvg) . '" width="100" height="100" alt="Opportunity Photos">',
                    $body);
            }

            if (str_contains($body, '{{opportunity_qr}}')) {
                $mobileUrl = route('mobile.opportunity.show', $opportunity->id);
                $qrSvg     = (string) \SimpleSoftwareIO\QrCode\Facades\QrCode::size(100)->margin(1)->generate($mobileUrl);
                $body = str_replace('{{opportunity_qr}}',
                    '<img src="data:image/svg+xml;base64,' . base64_encode($qrSvg) . '" width="100" height="100" alt="Opportunity">',
                    $body);
            }
        }

        return $body;
    }

    /**
     * Build an HTML table of material items grouped by room for the given sale.
     */
    private function buildFlooringTable(Sale $sale): string
    {
        $sale->loadMissing('rooms.items');

        $rows = '';
        $hasRows = false;

        foreach ($sale->rooms as $room) {
            $materialItems = $room->items->where('type', 'material')->values();

            if ($materialItems->isEmpty()) {
                continue;
            }

            $hasRows = true;
            $count   = $materialItems->count();

            foreach ($materialItems as $i => $item) {
                $productName = implode(' — ', array_filter([
                    $item->product_type,
                    $item->manufacturer,
                    $item->style,
                    $item->color_item_number,
                ])) ?: ($item->item_name ?? '');

                $rows .= '<tr>';

                if ($i === 0) {
                    $rows .= '<td rowspan="' . $count . '" style="vertical-align:top; font-weight:bold; padding:6px 8px; border:1px solid #ccc; background:#f5f5f5;">'
                           . e($room->room_name)
                           . '</td>';
                }

                $rows .= '<td style="padding:6px 8px; border:1px solid #ccc;">' . e($productName) . '</td>';
                $rows .= '<td style="padding:6px 8px; border:1px solid #ccc; text-align:center;">' . number_format((float) $item->quantity, 2) . '</td>';
                $rows .= '<td style="padding:6px 8px; border:1px solid #ccc; text-align:center;">' . e($item->unit ?? '') . '</td>';
                $rows .= '</tr>';
            }
        }

        if (! $hasRows) {
            return '<p style="color:#888; font-style:italic;">No material items found on this sale.</p>';
        }

        return '<table style="width:100%; border-collapse:collapse; font-size:11px;">'
             . '<thead>'
             . '<tr style="background:#1d4ed8; color:#fff;">'
             . '<th style="padding:7px 8px; text-align:left; border:1px solid #1d4ed8;">Room</th>'
             . '<th style="padding:7px 8px; text-align:left; border:1px solid #1d4ed8;">Product</th>'
             . '<th style="padding:7px 8px; text-align:center; border:1px solid #1d4ed8;">Qty</th>'
             . '<th style="padding:7px 8px; text-align:center; border:1px solid #1d4ed8;">Unit</th>'
             . '</tr>'
             . '</thead>'
             . '<tbody>' . $rows . '</tbody>'
             . '</table>';
    }
}
